# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-11 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20210711_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
