# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20210711_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Profile')),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Image')),
            ],
        ),
    ]
