# Generated by Django 3.2.5 on 2021-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_auto_20210713_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
